version: "3.8"
services:
  eureka-server:
    build: 
      context: .
      dockerfile: EurekaServer/Dockerfile
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8085:8085"
    networks:
      - ms-network
    environment:
      server.port: 8085

  eureka-client-1:
    build:
      context: .
      dockerfile: EurekaFirstClient/Dockerfile
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [ node.role == worker ]
    ports:
      - "8001-8100:8001"
    depends_on:
      - eureka-server
    networks:
      - ms-network
    environment:
      - "server.port=8001"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka"
  
  gateway-example:
    build: 
      context: .
      dockerfile: GatewayExample/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - eureka-client-1
    networks:
      - ms-network
    environment:
      - "server.port=8080"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka"

networks:
  ms-network:
    driver: bridge
      


  